services:
  - type: web
    name: video-api-1-2
    runtime: python
    buildCommand: pip install --upgrade --no-cache-dir -r requirements.txt
    startCommand: gunicorn server:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
